In [10]:
import numpy as np
def initialize_weights(layers = [784, 60, 60, 10]):
    # The following Python lists will contain numpy matrices
    # connected the layers in the neural network 
    W = [[0.0]]
    B = [[0.0]]
    for i in range(1, len(layers)):
        # The scaling factor below is from a research paper
        w_temp = np.random.randn(layers[i], layers[i-1])*np.sqrt(2/layers[i-1])
        b_temp = np.random.randn(layers[i], 1)*np.sqrt(2/layers[i-1])
    
        W.append(w_temp)
        B.append(b_temp)
    return W, B

In [11]:
initialize_weights(layers = [4, 3, 2, 1])

([[0.0],
  array([[ 0.14990995, -0.7896968 ,  0.01409911,  0.21054217],
         [-0.42662443,  0.25687521, -0.29566598, -0.67089598],
         [ 0.27317635, -0.32256117,  0.80015191,  0.40381934]]),
  array([[ 0.84956588, -0.80390908, -0.90526968],
         [-0.0245937 ,  0.01244937,  2.16657276]]),
  array([[ 1.27272103, -1.14255881]])],
 [[0.0],
  array([[-0.83628288],
         [-0.3225988 ],
         [ 0.25716097]]),
  array([[-0.78846408],
         [ 0.19623147]]),
  array([[0.21449042]])])